// pages/portfolio/index.vue
<template>
  <div>
    <NuxtLink to="/">
      <img
        src="~/assets/images/bryson-avatar.jpg"
        class="borderCircle mx-auto h-36 w-36"
        alt="bryson-avatar-img"
      />
    </NuxtLink>

    <div>
      <!-- Languages --->
      <Languages />
      <!-- Tech Stack --->
      <TechStack />
      <!-- Projects --->
      <Projects />
      <!-- Github --->
      <Github />
      <!-- Contact --->
      <Contact />
    </div>
    <div style="margin: 3rem 0 0">
      <NuxtLink class="text-zinc-600 dark:text-primary" href="/"
        >← Back to home</NuxtLink
      >
    </div>
  </div>
</template>

<script setup lang="ts">
import Github from '@/components/Github.vue';
import Languages from '@/components/Languages.vue';
import Projects from '@/components/Projects.vue';
import TechStack from '@/components/TechStack.vue';
useHead({
  title: 'Bryson Ward | Portfolio',
  meta: [{ name: 'description', content: 'Bryson Ward: Full Stack Engineer.' }],
});
</script>

<style scoped>
.borderCircle {
  border-radius: 9999px;
}
</style>

// src/routes/portfolio.svelte
<script lang="ts">
import Contact from "../components/Contact.svelte";
import Github from "../components/Github.svelte";
import Projects from "../components/Projects.svelte";
import TechStack from "../components/TechStack.svelte";
import Web3 from "../components/Web3.svelte";
import Languages from "../components/Languages.svelte";
import avatarImage from '../components/images/bryson-avatar.jpg'
</script>

<svelte:head>
	<title>DevBryson | Portfolio</title>
</svelte:head>


    <a href="/">
      <img
        src={avatarImage}
        class="borderCircle mx-auto"
        height={108}
        width={108}
        alt="bryson-avatar-img"
      />
    </a>



<div>
    <!-- Languages --->
    <Languages />
     <!-- Tech Stack --->
     <TechStack />
      <!-- Web3 --->
      <Web3 />
       <!-- Projects --->
       <Projects />
       <!-- Github --->
       <Github />
        <!-- Contact --->
        <Contact />
</div>
<div style="margin: 3rem 0 0;">
         
  <a href="/">← Back to home</a>

</div>


<style>
     .borderCircle {
    border-radius: 9999px;
  }
</style>
